version: 2
jobs:
  
  checkout:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - save_cache:
          key: source-code-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/repo

  create-env:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - restore_cache:
          keys:
            - source-code-{{ .Branch }}-{{ .Revision }}
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: code-and-env-{{ .Branch }}-{{ .Revision }}
          paths:
            - '~/repo'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.6/site-packages'

  test:  
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - code-and-env-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            pipenv run python manage.py test

  lint:  
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - code-and-env-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            pipenv run python manage.py test

  build:  
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - code-and-env-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Build docker image
          command: |
            echo "This is a deploy script"
      - run:
          name: Upload docker image
          command: |
            echo "This is a deploy script"

  deploy: &deploy  
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: Build docker image
          command: |
            echo "Rebuild kubernetes manifests and do kubectl apply"
      
  deploy-staging: *deploy
  deploy-prod: *deploy









workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - create-env:
          requires:
            - checkout
      - test:
          requires:
            - create-env
      - lint:
          requires:
            - create-env
      - build:
          requires:
            - test
            - lint
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - approve:
          type: approval
          requires:
            - deploy-staging
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - approve
          filters:
            branches:
              only:
                - master
     