name: Build and test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8' # Semantic version range syntax or exact version of a Python version
          architecture: 'x64' # Optional - x64 or x86, defaults to x64
      - name: Install system packages
        run: |
          sudo apt-get install -y libpq-dev
      - name: Install application dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
