name: Build and test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files
        run: ls -lah
      - uses: actions/upload-artifact@v1
        with:
          name: source-code
          path: .
  create_env:
    name: Create env
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: source-code
          path: .
      - name: List files
        run: ls -lah
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install system packages
        run: |
          sudo apt-get install -y libpq-dev
      - name: Install application dependencies
        run: |
          sudo pip3 install pipenv
          pipenv install
      - name: List files
        run: ls -lah
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: create_env
    steps:
      - name: List files
        run: ls -lah
      - name: Run tests
        run: |
          pipenv run python manage.py test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: create_env
    steps:
      - name: List files
        run: ls -lah
      - name: Run pyflake8
        run: |
          pipenv run pylint templates
        